config/routes.rb
Rails.application.routes.draw do

  resources :members
  root 'home#index'

  match 'accounts/login', :to => "accounts#login", :as => "login", :via => [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

	def index

	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/accounts/login.html.erb
<div class="container login">

	<div class="row" style="padding: 10px;">
		<div class="col-lg-6 col-md-6 col-sm-12 login-card">

			<div class="avatar mx-auto text-center"><img src="<%= image_path('person.png')%>" class="rounded-circle avatar">
            </div>
			

	        <h2> Sign In </h2>
	        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
	         <div  class="input-group">
                <span class="input-group-addon"><i class="fas fa-user"></i></span>
                <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">                                        
            </div>
                
            <div class="input-group">
                <span class="input-group-addon"><i class="fas fa-unlock"></i></span>
                <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
            </div>
            <div class="input-group" style="padding-left: 37px">
            	<%= button_tag "Sign In", :class => "btn btn-primary" %>
            </div>
	    </div>
	</div>

</div>

<!-- Footer -->
<footer class="page-footer font-small unique-color-dark mt-4">
<!-- Copyright -->
<div class="footer-copyright text-center py-3 fixed-bottom">© 2018 Copyright:
  <a href="#"> <img src="<%= image_path('sr.png') %>" style="width: 20px;"></img> Sreeyesh A </a>
</div>
<!-- Copyright -->

</footer>
<!-- Footer -->

<style type="text/css">
body {
	background-image: url("<%= image_path('login_background.jpg')%>");
	background-size: cover;
	background-attachment: fixed;
	background-repeat: no-repeat;
	background-position: center
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamFund</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.6/css/mdb.min.css" />

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.6/js/mdb.min.js"></script>

    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark nav-custom">
      <!-- Brand -->
      <a class="navbar-brand" href="<%= root_path %>"><img class="logo" src="<%= image_path('nmandea.png') %>"></a>

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#"> <i class="fas fa-credit-card"></i> Team Fund </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> <i class="fas fa-gift"></i> Gifts </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> <i class="fas fa-utensils"></i> Treat </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= members_path() %>"><i class="fas fa-users"></i> Members </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= login_path() %>"><i class="fas fa-sign-in-alt"></i> Sign In </a>
          </li> 
        </ul>
      </div> 
    </nav>

    
  <a id="back-to-top" href="#" class="btn btn-danger btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><i class="fas fa-arrow-up"></i></a>
    <%= yield %>
  </body>
</html>